from function.clearSpecialCHAR import clearSpecialCHAR

def getList(text):
  
  listTEXT = []
  #
  for palabra in text.split():
    palabra = clearSpecialCHAR(palabra)
    # Transformar a minúscula
    palabra = palabra.lower()
    if palabra != '':
      if len(palabra) - 3 >= 9:
        n = 9
      else:
        n = len(palabra) - 3
        if n < 0:
          n = 0
      for i in range(n, 0, -1):
        if lista_sufijos.get(palabra[-i:]):
          palabra = palabra[:-i]
          break
      listTEXT.append(palabra)
  #
  return listTEXT

lista_sufijos = {
    "able": True,
    "ación": True,
    "ancia": True,
    "ante": True,
    "anza": True,
    "ario": True,
    "asco": True,
    "ato": True,
    "ble": True,
    "ción": True,
    "dor": True,
    "dura": True,
    "eño": True,
    "esco": True,
    "és": True,
    "ez": True,
    "fobia": True,
    "fono": True,
    "genio": True,
    "grafía": True,
    "ico": True,
    "idad": True,
    "iego": True,
    "iento": True,
    "ismo": True,
    "ista": True,
    "itis": True,
    "ivo": True,
    "logía": True,
    "mento": True,
    "ncia": True,
    "nte": True,
    "oide": True,
    "or": True,
    "oso": True,
    "sión": True,
    "ura": True,
    "voro": True,
    "zuelo": True,
    "iador": True,
    "iadora": True,
    "ar": True,
    "al": True,
    "ón": True,
    "ito": True,
    "ita": True,
    "ón": True,
    "ano": True,
    "ana": True,
    "ino": True,
    "ina": True,
    "aje": True,
    "aje": True,
    "oría": True,
    "ismo": True,
    "ístico": True,
    "ístico": True,
    "ificación": True,
    "icación": True,
    "era": True,
    "ero": True,
    "illo": True,
    "illo": True,
    "ura": True,
    "dad": True,
    "tud": True,
    "dumbre": True,
    "dad": True,
    "oría": True,
    "ería": True,
    "ez": True,
    "ez": True,
    "ería": True,
    "azo": True,
    "azo": True,
    "ito": True,
    "ita": True,
    "ero": True,
    "era": True,
    "oso": True,
    "osa": True,
    "illo": True,
    "illa": True,
    "ón": True,
    "or": True,
    "ora": True,
    "oso": True,
    "osa": True,
    "al": True,
    "al": True,
    "ento": True,
    "iento": True,
    "al": True,
    "il": True,
    "il": True,
    "ería": True,
    "ería": True,
    "érrimo": True,
    "érrimo": True,
    "azo": True,
    "azo": True,
    "acho": True,
    "acha": True,
    "aco": True,
    "aca": True,
    "ato": True,
    "ata": True,
    "cida": True,
    "cido": True,
    "cería": True,
    "cero": True,
    "cracia": True,
    "crata": True,
    "dad": True,
    "dor": True,
    "dora": True,
    "dumbre": True,
    "ear": True,
    "ear": True,
    "ería": True,
    "ero": True,
    "eria": True,
    "ero": True,
    "és": True,
    "ez": True,
    "eza": True,
    "filo": True,
    "fobia": True,
    "fobo": True,
    "grama": True,
    "grafo": True,
    "ícola": True,
    "ícola": True,
    "ico": True,
    "illa": True,
    "illo": True,
    "ina": True,
    "ino": True,
    "ismo": True,
    "ista": True,
    "izar": True,
    "izar": True,
    "mente": True,
    "mente": True,
    "ón": True,
    "ón": True,
    "ona": True,
    "or": True,
    "oso": True,
    "oso": True,
    "ote": True,
    "ote": True,
    "triz": True,
    "triz": True,
    "ulento": True,
    "ulenta": True,
    "undio": True,
    "undia": True,
    "ura": True,
    "uro": True,
    "uro": True,
    "uro": True,
    "zuela": True,
    "zuelo": True,
    "abas": True,
    "ábamos": True,
    "abais": True,
    "aban": True,
    "ada": True,
    "ado": True,
    "amos": True,
    "ando": True,
    "ar": True,
    "ara": True,
    "arais": True,
    "aran": True,
    "aras": True,
    "are": True,
    "aremos": True,
    "aréis": True,
    "aría": True,
    "aríais": True,
    "aríamos": True,
    "arían": True,
    "arías": True,
    "aron": True,
    "as": True,
    "ás": True,
    "ás": True,
    "aste": True,
    "asteis": True,
    "é": True,
    "emos": True,
    "éis": True,
    "en": True,
    "es": True,
    "és": True,
    "ido": True,
    "iendo": True,
    "imos": True,
    "ir": True,
    "iendo": True,
    "irá": True,
    "irán": True,
    "iría": True,
    "iríamos": True,
    "irían": True,
    "irías": True,
    "o": True,
    "ía": True,
    "ías": True,
    "íamos": True,
    "íais": True,
    "ían": True,
    "ió": True,
    "í": True,
    "éis": True,
    "én": True,
    "idez": True
}
